/*

 GAME_OVER_SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Yunus\Documents\gameboy\tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define game_over_screenWidth 20
#define game_over_screenHeight 18
#define game_over_screenBank 0

extern unsigned char game_over_screen[];

/* End of GAME_OVER_SCREEN.H */
