/*

 TITLE_SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Yunus\Documents\gameboy\tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define title_screenWidth 20
#define title_screenHeight 18
#define title_screenBank 0

extern unsigned char title_screen[];

/* End of TITLE_SCREEN.H */
